const players = [
  // BATSMEN
  { name: "Virat Kohli", age: 35, country: "India", role: "Batsman", basePrice: 2, isCapped: true, imageUrl: "https://ui-avatars.com/api/?name=Virat+Kohli&background=0D8ABC&color=fff&size=200", battingStats: { innings: 237, runs: 4188, strikeRate: 137.96, average: 52.65, highScore: 122, fifties: 38, hundreds: 1 } },
  { name: "Rohit Sharma", age: 37, country: "India", role: "Batsman", basePrice: 2, isCapped: true, imageUrl: "https://ui-avatars.com/api/?name=Rohit+Sharma&background=E53935&color=fff&size=200", battingStats: { innings: 151, runs: 4231, strikeRate: 140.89, average: 32.05, highScore: 118, fifties: 26, hundreds: 4 } },
  { name: "Shubman Gill", age: 24, country: "India", role: "Batsman", basePrice: 1, isCapped: true, imageUrl: "https://ui-avatars.com/api/?name=Shubman+Gill&background=43A047&color=fff&size=200", battingStats: { innings: 67, runs: 2284, strikeRate: 148.83, average: 39.03, highScore: 129, fifties: 14, hundreds: 3 } },
  { name: "KL Rahul", age: 32, country: "India", role: "Batsman", basePrice: 1, isCapped: true, imageUrl: "https://ui-avatars.com/api/?name=KL+Rahul&background=8E24AA&color=fff&size=200", battingStats: { innings: 109, runs: 3452, strikeRate: 136.05, average: 45.42, highScore: 132, fifties: 25, hundreds: 1 } },
  { name: "David Warner", age: 37, country: "Australia", role: "Batsman", basePrice: 1, isCapped: true, imageUrl: "https://ui-avatars.com/api/?name=David+Warner&background=FFB300&color=fff&size=200", battingStats: { innings: 107, runs: 3277, strikeRate: 143.19, average: 33.44, highScore: 126, fifties: 24, hundreds: 4 } },
  { name: "Jos Buttler", age: 33, country: "England", role: "Batsman", basePrice: 1, isCapped: true, imageUrl: "https://ui-avatars.com/api/?name=Jos+Buttler&background=1565C0&color=fff&size=200", battingStats: { innings: 103, runs: 3582, strikeRate: 150.21, average: 39.36, highScore: 124, fifties: 24, hundreds: 4 } },
  { name: "Faf du Plessis", age: 39, country: "South Africa", role: "Batsman", basePrice: 0.50, isCapped: true, imageUrl: "https://ui-avatars.com/api/?name=Faf+du+Plessis&background=00897B&color=fff&size=200", battingStats: { innings: 96, runs: 2935, strikeRate: 136.78, average: 34.53, highScore: 119, fifties: 20, hundreds: 2 } },
  { name: "Ruturaj Gaikwad", age: 27, country: "India", role: "Batsman", basePrice: 0.50, isCapped: true, imageUrl: "https://ui-avatars.com/api/?name=Ruturaj+Gaikwad&background=F4511E&color=fff&size=200", battingStats: { innings: 75, runs: 2389, strikeRate: 142.67, average: 36.75, highScore: 101, fifties: 18, hundreds: 1 } },

  // BOWLERS
  { name: "Jasprit Bumrah", age: 30, country: "India", role: "Bowler", basePrice: 2, isCapped: true, imageUrl: "https://ui-avatars.com/api/?name=Jasprit+Bumrah&background=0D8ABC&color=fff&size=200", bowlingStats: { innings: 120, wickets: 145, economy: 7.39, average: 23.27, bestFigures: "5/10", fourWickets: 3 } },
  { name: "Yuzvendra Chahal", age: 33, country: "India", role: "Bowler", basePrice: 1, isCapped: true, imageUrl: "https://ui-avatars.com/api/?name=Yuzvendra+Chahal&background=E53935&color=fff&size=200", bowlingStats: { innings: 130, wickets: 187, economy: 7.59, average: 22.87, bestFigures: "5/40", fourWickets: 7 } },
  { name: "Rashid Khan", age: 25, country: "Afghanistan", role: "Bowler", basePrice: 2, isCapped: true, imageUrl: "https://ui-avatars.com/api/?name=Rashid+Khan&background=43A047&color=fff&size=200", bowlingStats: { innings: 122, wickets: 165, economy: 6.71, average: 20.51, bestFigures: "4/15", fourWickets: 9 } },
  { name: "Trent Boult", age: 34, country: "New Zealand", role: "Bowler", basePrice: 0.50, isCapped: true, imageUrl: "https://ui-avatars.com/api/?name=Trent+Boult&background=8E24AA&color=fff&size=200", bowlingStats: { innings: 99, wickets: 121, economy: 8.02, average: 26.71, bestFigures: "4/18", fourWickets: 4 } },
  { name: "Mohammed Shami", age: 33, country: "India", role: "Bowler", basePrice: 1, isCapped: true, imageUrl: "https://ui-avatars.com/api/?name=Mohammed+Shami&background=FFB300&color=fff&size=200", bowlingStats: { innings: 87, wickets: 98, economy: 8.57, average: 27.44, bestFigures: "4/16", fourWickets: 3 } },
  { name: "Kagiso Rabada", age: 29, country: "South Africa", role: "Bowler", basePrice: 1, isCapped: true, imageUrl: "https://ui-avatars.com/api/?name=Kagiso+Rabada&background=1565C0&color=fff&size=200", bowlingStats: { innings: 89, wickets: 112, economy: 8.21, average: 25.63, bestFigures: "4/21", fourWickets: 5 } },
  { name: "Pat Cummins", age: 31, country: "Australia", role: "Bowler", basePrice: 1, isCapped: true, imageUrl: "https://ui-avatars.com/api/?name=Pat+Cummins&background=00897B&color=fff&size=200", bowlingStats: { innings: 78, wickets: 89, economy: 8.93, average: 30.12, bestFigures: "4/14", fourWickets: 2 } },
  { name: "Arshdeep Singh", age: 25, country: "India", role: "Bowler", basePrice: 0.50, isCapped: true, imageUrl: "https://ui-avatars.com/api/?name=Arshdeep+Singh&background=F4511E&color=fff&size=200", bowlingStats: { innings: 65, wickets: 78, economy: 8.44, average: 26.85, bestFigures: "4/9", fourWickets: 3 } },
  { name: "Wanindu Hasaranga", age: 26, country: "Sri Lanka", role: "Bowler", basePrice: 0.50, isCapped: true, imageUrl: "https://ui-avatars.com/api/?name=Wanindu+Hasaranga&background=0D8ABC&color=fff&size=200", bowlingStats: { innings: 95, wickets: 128, economy: 7.22, average: 19.87, bestFigures: "6/19", fourWickets: 8 } },

  // ALL-ROUNDERS
  { name: "Hardik Pandya", age: 30, country: "India", role: "All-rounder", basePrice: 2, isCapped: true, imageUrl: "https://ui-avatars.com/api/?name=Hardik+Pandya&background=E53935&color=fff&size=200", allRounderStats: { innings: 112, runs: 2376, strikeRate: 148.52, wickets: 75, economy: 8.83 } },
  { name: "Ravindra Jadeja", age: 35, country: "India", role: "All-rounder", basePrice: 2, isCapped: true, imageUrl: "https://ui-avatars.com/api/?name=Ravindra+Jadeja&background=43A047&color=fff&size=200", allRounderStats: { innings: 98, runs: 1578, strikeRate: 142.37, wickets: 132, economy: 7.61 } },
  { name: "Ben Stokes", age: 32, country: "England", role: "All-rounder", basePrice: 2, isCapped: true, imageUrl: "https://ui-avatars.com/api/?name=Ben+Stokes&background=8E24AA&color=fff&size=200", allRounderStats: { innings: 88, runs: 1939, strikeRate: 143.71, wickets: 63, economy: 8.42 } },
  { name: "Axar Patel", age: 30, country: "India", role: "All-rounder", basePrice: 1, isCapped: true, imageUrl: "https://ui-avatars.com/api/?name=Axar+Patel&background=FFB300&color=fff&size=200", allRounderStats: { innings: 89, runs: 1245, strikeRate: 153.88, wickets: 98, economy: 7.28 } },
  { name: "Glenn Maxwell", age: 35, country: "Australia", role: "All-rounder", basePrice: 1, isCapped: true, imageUrl: "https://ui-avatars.com/api/?name=Glenn+Maxwell&background=1565C0&color=fff&size=200", allRounderStats: { innings: 115, runs: 3180, strikeRate: 157.94, wickets: 47, economy: 8.12 } },
  { name: "Andre Russell", age: 35, country: "West Indies", role: "All-rounder", basePrice: 1, isCapped: true, imageUrl: "https://ui-avatars.com/api/?name=Andre+Russell&background=00897B&color=fff&size=200", allRounderStats: { innings: 108, runs: 2734, strikeRate: 178.43, wickets: 87, economy: 9.12 } },
  { name: "Shardul Thakur", age: 32, country: "India", role: "All-rounder", basePrice: 0.30, isCapped: true, imageUrl: "https://ui-avatars.com/api/?name=Shardul+Thakur&background=F4511E&color=fff&size=200", allRounderStats: { innings: 72, runs: 678, strikeRate: 144.87, wickets: 82, economy: 9.34 } },
  { name: "Mitchell Marsh", age: 32, country: "Australia", role: "All-rounder", basePrice: 0.50, isCapped: true, imageUrl: "https://ui-avatars.com/api/?name=Mitchell+Marsh&background=0D8ABC&color=fff&size=200", allRounderStats: { innings: 79, runs: 1876, strikeRate: 145.22, wickets: 38, economy: 8.76 } },

  // WICKET-KEEPERS
  { name: "MS Dhoni", age: 42, country: "India", role: "Wicket-keeper", basePrice: 2, isCapped: true, imageUrl: "https://ui-avatars.com/api/?name=MS+Dhoni&background=E53935&color=fff&size=200", keeperStats: { innings: 213, runs: 4978, strikeRate: 135.92, average: 38.09, dismissals: 195 } },
  { name: "Rishabh Pant", age: 26, country: "India", role: "Wicket-keeper", basePrice: 2, isCapped: true, imageUrl: "https://ui-avatars.com/api/?name=Rishabh+Pant&background=43A047&color=fff&size=200", keeperStats: { innings: 98, runs: 2838, strikeRate: 148.72, average: 35.47, dismissals: 87 } },
  { name: "Quinton de Kock", age: 31, country: "South Africa", role: "Wicket-keeper", basePrice: 1, isCapped: true, imageUrl: "https://ui-avatars.com/api/?name=Quinton+de+Kock&background=8E24AA&color=fff&size=200", keeperStats: { innings: 112, runs: 3476, strikeRate: 140.53, average: 34.76, dismissals: 98 } },
  { name: "Ishan Kishan", age: 25, country: "India", role: "Wicket-keeper", basePrice: 0.50, isCapped: true, imageUrl: "https://ui-avatars.com/api/?name=Ishan+Kishan&background=FFB300&color=fff&size=200", keeperStats: { innings: 78, runs: 2134, strikeRate: 145.88, average: 30.49, dismissals: 62 } },
  { name: "Sanju Samson", age: 29, country: "India", role: "Wicket-keeper", basePrice: 1, isCapped: true, imageUrl: "https://ui-avatars.com/api/?name=Sanju+Samson&background=1565C0&color=fff&size=200", keeperStats: { innings: 102, runs: 2987, strikeRate: 143.27, average: 34.73, dismissals: 76 } },
]

module.exports = players